repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.4
    hooks:
    - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: detect-private-key
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: master  # Use the revision sha / tag you want to point at
  #   hooks:
  #   - id: isort
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: master
  #   hooks:
  #   - id: mypy
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: master
  #   hooks:
  #   - id: blacken-docs
  # - repo: https://github.com/asottile/dead
  #   rev: master
  #   hooks:
  #   - id: dead
  # - repo: https://github.com/PyCQA/pylint
  #   rev: master
  #   hooks:
  #   - id: pylint
  # - repo: https://github.com/PyCQA/bandit
  #   rev: master
  #   hooks:
  #   - id: bandit
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: master
  #   hooks:
  #   - id: detect-secrets
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
